export const brandReference = {
  colors: {
    background: {
      hex: "#ffffff",
      token: "background",
      usage: "Primary page background.",
    },
    foreground: {
      hex: "#33373d",
      token: "foreground",
      usage: "Default text color.",
    },
    tan: {
      hex: "#f4f2ed",
      token: "brand-tan",
      usage: "Warm off-white accent bands only; avoid tan-heavy pages.",
    },
    blue: {
      hex: "#213949",
      token: "brand-blue",
      usage: "Primary brand color for headings, dark sections, and CTAs.",
    },
    accent: {
      hex: "#b57b58",
      token: "brand-accent",
      usage: "Warm CTA/accent color. Use sparingly for action and emphasis.",
    },
    greyLight: {
      hex: "#9aa0a9",
      token: "brand-grey-light",
      usage: "Soft borders, dividers, and quiet metadata.",
    },
    greyMid: {
      hex: "#7a7a7a",
      token: "brand-grey-mid",
      usage: "Body text and secondary explanations.",
    },
    greyDark: {
      hex: "#33373d",
      token: "brand-grey-dark",
      usage: "Primary dark text when brand blue is too strong.",
    },
  },
  preferences: [
    "Use a navy and white foundation with restrained grey copy.",
    "Avoid tan-heavy layouts; tan is a supporting surface color.",
    "Use the warm accent for primary conversion buttons and key proof cues.",
    "Buttons should be squared modern rectangles with modest radius, not pills.",
    "Do not use decorative colored side strips on cards.",
    "Use realistic financial-services imagery with tasteful faith cues.",
    "Avoid environmental nonprofit imagery, shame-based debt visuals, and text baked into images.",
    "Keep copy short and scan-friendly for paid landing-page traffic.",
  ],
  logos: [
    "/brand/logo-full-color.svg",
    "/brand/logo-full-color.png",
    "/brand/logo-white.svg",
    "/brand/logo-white.png",
    "/brand/logo-mark.svg",
    "/brand/logo-mark-white.svg",
    "/brand/logo-horizontal-tagline.svg",
    "/brand/new-logos/",
  ],
  favicons: [
    "/favicon.ico",
    "/favicon.svg",
    "/favicon-96x96.png",
    "/apple-touch-icon.png",
    "/apple-icon.png",
    "/icon.png",
    "/web-app-manifest-192x192.png",
    "/web-app-manifest-512x512.png",
    "/site.webmanifest",
  ],
  pageImages: [
    "/brand/credit-score-graphic.png",
    "/brand/generated/v002/church-lobby-advisor-family-v002.png",
    "/brand/generated/v003/advisor-family-testimonial-v003.png",
    "/brand/generated/v003/advisor-phone-support-bubble-v003.png",
    "/brand/generated/v004/church-lobby-standing-advisor-family-v004.png",
    "/brand/generated/v004/confident-borrower-family-phone-v004.png",
    "/brand/generated/v004/hero-faith-river-background-v004.png",
    "/brand/generated/v005/hero-credit-card-debt-relief-v005.png",
    "/brand/generated/v005/hero-debt-relief-prayer-budget-v005.png",
    "/brand/generated/v005/resources-guidance-hero-v005.png",
    "/brand/generated/v006/credit-card-debt-relief-rectangle-v006.png",
    "/brand/generated/v006/debt-relief-budget-couple-v006.png",
    "/brand/generated/v006/resources-guidance-compact-hero-v006.png",
  ],
} as const;
