export const usStates = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
] as const;

export const surveyQuestions = {
  id: "river-relief-debt-review-core-v1",
  source: "river-relief-main-website",
  campaignDefault: "faith-based-debt-help",
  leadType: "debt-consolidation-intake",
  steps: [
    {
      id: "debtType",
      kind: "single-select",
      label: "What type of debt is giving you the most stress right now?",
      crmField: "debtType",
      required: true,
      options: [
        "Credit Card Debt",
        "Personal Loan Debt",
        "Another Kind Of Debt",
      ],
      affirmation:
        "Naming the pressure is a faithful first step toward Financial Stewardship.",
    },
    {
      id: "debtAmount",
      kind: "single-select",
      label: "How Much Debt Do You Currently Have?",
      crmField: "debtAmount",
      required: true,
      options: ["$0 - $30,000", "$30,000 - $50,000", "$50,000+"],
      affirmation:
        "A range is enough. River Relief can help you compare options without shame.",
    },
    {
      id: "paymentStruggleDuration",
      kind: "single-select",
      label: "How Long Have You Been Struggling With Payments?",
      crmField: "paymentStruggleDuration",
      required: true,
      options: ["Very Recently", "6 Months - 1 Year", "1-3 years", "3+ Years"],
      affirmation:
        "There is grace for every timeline. The next step can still be practical.",
    },
    {
      id: "stateOfResidence",
      kind: "state-select",
      label: "State of Residence*",
      title: "You Qualify For Debt Relief Options!",
      crmField: "stateOfResidence",
      required: true,
      options: usStates,
      affirmation:
        "State availability matters. This helps River Relief point you toward the right review path.",
    },
    {
      id: "contact",
      kind: "contact",
      title: "Debt Relief Options Found!",
      deliveryQuestion: "Where Should We Send Your Options?",
      required: true,
      fields: [
        { id: "firstName", label: "First name", type: "text", required: true },
        { id: "lastName", label: "Last name", type: "text", required: true },
        { id: "email", label: "Email", type: "email", required: true },
        { id: "phone", label: "Phone", type: "tel", required: true },
        {
          id: "tellUsMore",
          label: "Tell Us More",
          type: "textarea",
          required: false,
          placeholder: "Share anything helpful for the first conversation.",
        },
        {
          id: "consent",
          label:
            "By providing your phone number and checking this box, I consent to receive calls and text messages, including marketing and promotional messages, from River Relief, including through the use of an automatic telephone dialing system or an artificial or prerecorded voice, at any telephone number I provide. Msg and data rates may apply. Consent is not a condition for purchase. For text messages, reply STOP to cancel. If you choose not to consent, you may call us at 800-520-1758 to continue your inquiry.",
          type: "checkbox",
          required: true,
        },
      ],
      hiddenFields: [
        {
          id: "website",
          purpose: "Honeypot spam trap. Real visitors should leave it blank.",
        },
        {
          id: "landingPage",
          purpose: "Current path or landing-page variant.",
        },
        {
          id: "source",
          purpose: "Lead source identifier, for example amen-lp.",
        },
      ],
      affirmation: "The integrity of the upright guides them. Proverbs 11:3",
    },
  ],
} as const;

export type SurveyStep = (typeof surveyQuestions.steps)[number];
export type SurveyStepId = SurveyStep["id"];
